apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: '2018-03-20T19:01:36Z'
  generation: 9
  labels:
    app: nexus3
  name: nexus3
  namespace: bc-nexus
  resourceVersion: '797138'
  selfLink: /apis/apps.openshift.io/v1/namespaces/bc-nexus/deploymentconfigs/nexus3
  uid: 1d0d96cd-2c71-11e8-9d34-166b4f376a2c
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: nexus3
    deploymentconfig: nexus3
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Recreate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: nexus3
        deploymentconfig: nexus3
    spec:
      containers:
        - image: >-
            sonatype/nexus3@sha256:0c84eb9c3cec1e64c9ed19b1fca2eb272ce0e9429e146ace07f11a31455d1bdd
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
                - echo
                - ok
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: nexus3
          ports:
            - containerPort: 8081
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /repository/maven-public/
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              memory: 2Gi
            requests:
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /nexus-data
              name: nexus3-volume-1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: nexus3-volume-1
          persistentVolumeClaim:
            claimName: nexus-pvc
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - nexus3
        from:
          kind: ImageStreamTag
          name: 'nexus3:latest'
          namespace: bc-nexus
        lastTriggeredImage: >-
          sonatype/nexus3@sha256:0c84eb9c3cec1e64c9ed19b1fca2eb272ce0e9429e146ace07f11a31455d1bdd
      type: ImageChange
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2018-03-20T19:03:39Z'
      lastUpdateTime: '2018-03-20T19:08:01Z'
      message: replication controller "nexus3-2" successfully rolled out
      reason: NewReplicationControllerAvailable
      status: 'True'
      type: Progressing
    - lastTransitionTime: '2018-03-21T20:37:09Z'
      lastUpdateTime: '2018-03-21T20:37:09Z'
      message: Deployment config has minimum availability.
      status: 'True'
      type: Available
  details:
    causes:
      - type: ConfigChange
    message: config change
  latestVersion: 2
  observedGeneration: 9
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
