apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: '2018-03-22T16:32:44Z'
  generation: 12
  labels:
    app: tasks
  name: tasks
  namespace: bc-tasks-dev
  resourceVersion: '1377231'
  selfLink: /apis/apps.openshift.io/v1/namespaces/bc-tasks-dev/deploymentconfigs/tasks
  uid: a5da3878-2dee-11e8-9d34-166b4f376a2c
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: tasks
    deploymentconfig: tasks
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: tasks
        deploymentconfig: tasks
    spec:
      containers:
        - image: 'docker-registry.default.svc:5000/bc-tasks-dev/tasks:1.0-13'
          imagePullPolicy: IfNotPresent
          name: tasks
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opt/eap/standalone/configuration/application-users.properties
              name: jboss-config
              subPath: application-users.properties
            - mountPath: /opt/eap/standalone/configuration/application-roles.properties
              name: jboss-config1
              subPath: application-roles.properties
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: tasks-config
          name: jboss-config
        - configMap:
            defaultMode: 420
            name: tasks-config
          name: jboss-config1
  test: false
  triggers: []
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2018-03-22T19:18:58Z'
      lastUpdateTime: '2018-03-22T19:18:58Z'
      message: Deployment config has minimum availability.
      status: 'True'
      type: Available
    - lastTransitionTime: '2018-03-23T13:57:12Z'
      lastUpdateTime: '2018-03-23T13:57:14Z'
      message: replication controller "tasks-6" successfully rolled out
      reason: NewReplicationControllerAvailable
      status: 'True'
      type: Progressing
  details:
    causes:
      - type: Manual
    message: manual change
  latestVersion: 6
  observedGeneration: 12
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
